#!/usr/bin/env bash

INSTALL_PATH=~/.git-tree

ask() {
  while true; do
    read -p "$1 ([y]/n) " -r
    REPLY=${REPLY:-"y"}
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      return 0
    elif [[ $REPLY =~ ^[Nn]$ ]]; then
      return 1
    fi
  done
}

remove_line() {
  src=$1
  echo "Remove from $1:"

  shift
  line_no=1
  match=0
  while [ -n "$1" ]; do
    line=$(sed -n "$line_no,\$p" "$src" | \grep -m1 -nF "$1")
    if [ $? -ne 0 ]; then
      shift
      line_no=1
      continue
    fi
    line_no=$(( $(sed 's/:.*//' <<< "$line") + line_no - 1 ))
    content=$(sed 's/^[0-9]*://' <<< "$line")
    match=1
    echo    "  - Line #$line_no: $content"
    [ "$content" = "$1" ] || ask "    - Remove?"
    if [ $? -eq 0 ]; then
      temp=$(mktemp)
      awk -v n=$line_no 'NR == n {next} {print}' "$src" > "$temp" &&
        cat "$temp" > "$src" && rm -f "$temp" || break
      echo  "      - Removed"
    else
      echo  "      - Skipped"
      line_no=$(( line_no + 1 ))
    fi
  done
  [ $match -eq 0 ] && echo "  - Nothing found"
  echo
}

remove_gittreerc() {
  rm ~/.gittreerc
}

remove_source_from_bashrc() {
    remove_line ~/.bashrc \
    "[ -f ~/.gittreerc ] && source ~/.gittreerc"
}

uninstall_bash_preexec() {
  local has_bashrc_preexec=$(grep -c "source ~/.bash-preexec.sh" ~/.bashrc)
  if [ $has_bashrc_preexec -eq 0 ]; then
        rm ~/.bash-preexec.sh
  fi
}


remove_gittreerc
remove_source_from_bashrc
uninstall_bash_preexec
