name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git2go
      uses: actions/checkout@v3
      with:
        repository: libgit2/git2go
        path: git2go

    - name: Build static libgit2
      run: |
        git submodule update --init
        sudo apt-get install -y --no-install-recommends libssh2-1-dev
        sudo ./script/build-libgit2.sh --static --system
      working-directory: ./git2go

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Checkout git-tree
      uses: actions/checkout@v3
      with:
        path: main

    - name: Install dependencies
      run: go get .
      working-directory: ./main

    - name: Build
      run: go build -tags static,system_libgit2 -v ./...
      working-directory: ./main

    - name: Run tests
      run: go test -v ./...
      working-directory: ./main
